# These are supported funding model platforms
# To enable the GitHub Sponsor button and other funding links

# GitHub Sponsors
github: mcguiretechnology

# Custom (website, OpenCollective, etc.)
custom: ["https://mcguire.technology"]
