site_name: TruTemplate
theme:
  name: material
  palette:
    primary: 'purple'
    accent: 'indigo'

plugins:
  - search

nav:
  - Home: ../README.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Contributors: CONTRIBUTORS.md
  - Security: SECURITY.md
  - Support: SUPPORT.md
  - License: LICENSE.md
  - Custom Instructions: custom-instructions.md
  - Docs:
      - Features: docs/features.md
      - Android: docs/android/index.md
      - API: docs/api/index.md
      - Apple: docs/apple/index.md
      - Git: docs/git/index.md
      - GitHub: docs/github/index.md
      - Scripts: docs/scripts/index.md
      - VSCode: docs/vscode/index.md
      - WWW: docs/www/index.md
